services:
  jira-analytics:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
    volumes:
      - app_data:/app/analysis_cache
      - app_results:/app/pi_results
      - app_safety:/app/safety_data
      - app_docs:/app/doc
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  app_data:
  app_results:
  app_safety:
  app_docs: