"""
PDF Generator Base - Shared Module
Base class for PDF generation using ReportLab.

Provides common PDF generation functionality that can be extended
by application-specific generators.
"""

from reportlab.lib.pagesizes import A4, letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import List, Dict, Optional, Any
import logging
import base64

logger = logging.getLogger('PDFGenerator')

# Default page settings
DEFAULT_PAGE_SIZE = A4
DEFAULT_MARGIN = 72
DEFAULT_TOP_MARGIN = 72
DEFAULT_BOTTOM_MARGIN = 60


class NumberedCanvas:
    """Custom canvas for adding page numbers and footers."""
    
    def __init__(self, canvas, doc, footer_text: Optional[str] = None):
        self.canvas = canvas
        self.doc = doc
        self.footer_text = footer_text or "Generated by PerseusLeadTime"
    
    def draw_page_number_and_footer(self):
        """Draw page number and footer on each page."""
        page_num = self.canvas.getPageNumber()
        page_width = DEFAULT_PAGE_SIZE[0]
        
        # Page number (bottom right)
        self.canvas.setFont("Helvetica", 8)
        page_text = f"Page {page_num}"
        page_text_width = self.canvas.stringWidth(page_text)
        self.canvas.drawString(page_width - DEFAULT_MARGIN - page_text_width, 30, page_text)
        
        # Footer (bottom center)
        footer_width = self.canvas.stringWidth(self.footer_text)
        x_position = (page_width - footer_width) / 2
        self.canvas.drawString(x_position, 30, self.footer_text)


class PDFGeneratorBase:
    """
    Base class for PDF report generation.
    
    Provides common functionality for creating formatted PDF reports including:
    - Title pages
    - Headers and subheaders
    - Tables with styling
    - Images and charts
    - Page numbers and footers
    
    Example:
        >>> class MyPDFGenerator(PDFGeneratorBase):
        ...     def generate_content(self, data):
        ...         self.add_title("My Report")
        ...         self.add_text("Report content here")
        ...         self.add_table([["Header 1", "Header 2"], ["Data 1", "Data 2"]])
        >>>
        >>> generator = MyPDFGenerator()
        >>> generator.generate("output.pdf", data=my_data)
    """
    
    def __init__(self, title: str = "Jira Analytics Report", 
                 author: str = "PerseusLeadTime",
                 footer_text: Optional[str] = None):
        """
        Initialize PDF generator.
        
        Args:
            title: Document title
            author: Document author
            footer_text: Custom footer text
        """
        self.title = title
        self.author = author
        self.footer_text = footer_text or f"Generated by {author} - {datetime.now().year}"
        
        # Initialize styles
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        
        # Story elements (PDF content)
        self.elements = []
        
        logger.info(f"📝 PDFGeneratorBase initialized: {title}")
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles for the report."""
        # Title style
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#1E3A8A'),  # Dark blue
            alignment=TA_CENTER
        )
        
        # Heading style
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=12,
            spaceAfter=12,
            textColor=colors.HexColor('#2563EB')  # Blue
        )
        
        # Subheading style
        self.subheading_style = ParagraphStyle(
            'CustomSubheading',
            parent=self.styles['Heading3'],
            fontSize=14,
            spaceBefore=8,
            spaceAfter=8,
            textColor=colors.HexColor('#3B82F6')  # Light blue
        )
        
        # Normal with indentation
        self.indent_style = ParagraphStyle(
            'Indented',
            parent=self.styles['Normal'],
            leftIndent=20
        )
        
        # Italic style
        self.italic_style = ParagraphStyle(
            'CustomItalic',
            parent=self.styles['Italic'],
            textColor=colors.HexColor('#6B7280')  # Gray
        )
    
    def generate(self, output_path: str, data: Any = None) -> bool:
        """
        Generate PDF report.
        
        Args:
            output_path: Path to save the PDF
            data: Data to include in report
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # Reset elements
            self.elements = []
            
            # Create document
            doc = SimpleDocTemplate(
                output_path,
                pagesize=DEFAULT_PAGE_SIZE,
                rightMargin=DEFAULT_MARGIN,
                leftMargin=DEFAULT_MARGIN,
                topMargin=DEFAULT_TOP_MARGIN,
                bottomMargin=DEFAULT_BOTTOM_MARGIN,
                title=self.title,
                author=self.author
            )
            
            # Generate content (to be overridden by subclasses)
            self.generate_content(data)
            
            # Build PDF with page numbers and footer
            def add_page_elements(canvas, doc):
                numbered_canvas = NumberedCanvas(canvas, doc, self.footer_text)
                numbered_canvas.draw_page_number_and_footer()
            
            doc.build(self.elements, onFirstPage=add_page_elements, onLaterPages=add_page_elements)
            
            logger.info(f"✅ PDF generated successfully: {output_path}")
            return True
            
        except Exception as e:
            logger.error(f"🚩 PDF generation failed: {str(e)}")
            return False
    
    def generate_content(self, data: Any):
        """
        Generate PDF content. Override this in subclasses.
        
        Args:
            data: Data to include in report
        """
        self.add_title(self.title)
        self.add_timestamp()
        self.add_text("This is a base PDF report. Override generate_content() to customize.")
    
    # Content addition methods
    
    def add_title(self, text: str):
        """Add a document title."""
        self.elements.append(Spacer(1, 12))
        self.elements.append(Paragraph(text, self.title_style))
        self.elements.append(Spacer(1, 12))
    
    def add_heading(self, text: str, level: int = 1):
        """
        Add a heading.
        
        Args:
            text: Heading text
            level: Heading level (1, 2, or 3)
        """
        if level == 1:
            style = self.heading_style
        elif level == 2:
            style = self.subheading_style
        else:
            style = self.styles['Heading3']
        
        self.elements.append(Spacer(1, 6))
        self.elements.append(Paragraph(text, style))
        self.elements.append(Spacer(1, 6))
    
    def add_text(self, text: str, style: str = 'Normal', indent: bool = False):
        """
        Add a paragraph of text.
        
        Args:
            text: Text content
            style: Style name or 'Normal'
            indent: Whether to indent the paragraph
        """
        if indent:
            para_style = self.indent_style
        elif style == 'Normal':
            para_style = self.styles['Normal']
        elif style == 'Italic':
            para_style = self.italic_style
        else:
            para_style = self.styles.get(style, self.styles['Normal'])
        
        self.elements.append(Paragraph(text, para_style))
        self.elements.append(Spacer(1, 6))
    
    def add_timestamp(self):
        """Add generation timestamp."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.add_text(f"Generated on: {timestamp}", style='Italic')
    
    def add_spacer(self, height: float = 12):
        """
        Add vertical space.
        
        Args:
            height: Height in points
        """
        self.elements.append(Spacer(1, height))
    
    def add_page_break(self):
        """Add a page break."""
        self.elements.append(PageBreak())
    
    def add_table(self, data: List[List[Any]], col_widths: Optional[List[float]] = None,
                  style_name: str = 'default') -> bool:
        """
        Add a formatted table.
        
        Args:
            data: 2D list of table data
            col_widths: Optional list of column widths
            style_name: Table style ('default', 'alternating', 'simple', 'colorful')
            
        Returns:
            True if successful
        """
        if not data:
            logger.warning("⚠️ Cannot add empty table")
            return False
        
        try:
            # Create table
            table = Table(data, colWidths=col_widths)
            
            # Apply style
            table_style = self._get_table_style(style_name)
            table.setStyle(table_style)
            
            self.elements.append(table)
            self.elements.append(Spacer(1, 12))
            return True
            
        except Exception as e:
            logger.error(f"🚩 Failed to add table: {str(e)}")
            return False
    
    def _get_table_style(self, style_name: str) -> TableStyle:
        """Get predefined table style."""
        base_style = [
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]
        
        if style_name == 'default':
            base_style.append(('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')))
            base_style.append(('TEXTCOLOR', (0, 0), (-1, 0), colors.white))
        
        elif style_name == 'alternating':
            base_style.append(('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')))
            base_style.append(('TEXTCOLOR', (0, 0), (-1, 0), colors.white))
            base_style.append(('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F3F4F6')]))
        
        elif style_name == 'simple':
            base_style.append(('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E5E7EB')))
            base_style.append(('LINEABOVE', (0, 0), (-1, 0), 2, colors.HexColor('#2563EB')))
        
        elif style_name == 'colorful':
            base_style.append(('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#10B981')))
            base_style.append(('TEXTCOLOR', (0, 0), (-1, 0), colors.white))
        
        return TableStyle(base_style)
    
    def add_image(self, image_data: Any, width: float = 6*inch, 
                  height: float = 4*inch, caption: Optional[str] = None):
        """
        Add an image to the report.
        
        Args:
            image_data: Image data (file path, BytesIO, or base64 string)
            width: Image width
            height: Image height
            caption: Optional caption
        """
        try:
            # Handle different image data types
            if isinstance(image_data, str):
                if image_data.startswith('data:image'):
                    # Base64 encoded image
                    image_data = base64.b64decode(image_data.split(',')[1])
                    image_data = BytesIO(image_data)
                # else: assume it's a file path
            
            img = Image(image_data, width=width, height=height)
            self.elements.append(img)
            
            if caption:
                self.add_text(caption, style='Italic')
            
            self.elements.append(Spacer(1, 12))
            
        except Exception as e:
            logger.error(f"🚩 Failed to add image: {str(e)}")
    
    def add_list(self, items: List[str], bullet: str = '•'):
        """
        Add a bulleted list.
        
        Args:
            items: List of items
            bullet: Bullet character
        """
        for item in items:
            self.add_text(f"{bullet} {item}", indent=True)
    
    def add_key_value_table(self, data: Dict[str, Any], title: Optional[str] = None):
        """
        Add a key-value table for displaying metadata.
        
        Args:
            data: Dictionary of key-value pairs
            title: Optional table title
        """
        if title:
            self.add_heading(title, level=2)
        
        table_data = [[k, str(v)] for k, v in data.items()]
        
        table = Table(table_data, colWidths=[2*inch, 4*inch])
        table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F3F4F6')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        
        self.elements.append(table)
        self.elements.append(Spacer(1, 12))


# Convenience function for simple PDF generation
def generate_simple_pdf(output_path: str, title: str, content: List[Dict]) -> bool:
    """
    Generate a simple PDF with basic content.
    
    Args:
        output_path: Path to save PDF
        title: Document title
        content: List of content dictionaries with 'type' and data
        
    Returns:
        True if successful
        
    Example:
        >>> content = [
        ...     {'type': 'heading', 'text': 'Section 1'},
        ...     {'type': 'text', 'text': 'Some content'},
        ...     {'type': 'table', 'data': [['A', 'B'], ['1', '2']]}
        ... ]
        >>> generate_simple_pdf('report.pdf', 'My Report', content)
    """
    generator = PDFGeneratorBase(title=title)
    
    generator.add_title(title)
    generator.add_timestamp()
    
    for item in content:
        item_type = item.get('type')
        
        if item_type == 'heading':
            generator.add_heading(item['text'], level=item.get('level', 1))
        elif item_type == 'text':
            generator.add_text(item['text'])
        elif item_type == 'table':
            generator.add_table(item['data'], style_name=item.get('style', 'default'))
        elif item_type == 'image':
            generator.add_image(item['data'], caption=item.get('caption'))
        elif item_type == 'list':
            generator.add_list(item['items'])
        elif item_type == 'spacer':
            generator.add_spacer(item.get('height', 12))
        elif item_type == 'page_break':
            generator.add_page_break()
    
    return generator.generate(output_path)
